services:
  db-dev:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gollman
    ports:
      - "5432:5432"
    volumes:
      - pg-data-dev:/var/lib/postgresql/data
  db-staging:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db-staging
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gollman
    ports:
      - "5433:5432"
    volumes:
      - pg-data-staging:/var/lib/postgresql/data

volumes:
  pg-data-dev:
  pg-data-staging:
