mistral:
  apiKey:
  timeout: "15s"
  maxReqPerSec: 1

postgres:
  host: localhost
  port: "5433"
  user: postgres
  password: password
  database: gollman

fileStore:
  local:
    path: uploads

agent:
  docstore: pgvector
  sessionMessageLimit: 10
  embeddingModel: mistral/mistral-embed
  completionModel: mistral/mistral-small